version: '3.8'
services:
  jenkins:
    image: misticar/myjenkins-blueocean:2.3
    user: root
    networks: 
      jenkins :
        aliases: 
          - jenkins1
    environment:
      - DOCKER_HOST=tcp://docker:2376 
      - DOCKER_CERT_PATH=/certs/client 
      - DOCKER_TLS_VERIFY= 1
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home 
      - jenkins-docker-certs:/certs/client:ro

networks:
  jenkins :

volumes:
  jenkins-data: {}
  jenkins-docker-certs: {}



  # Error response from daemon: create _jenkins-data: "_jenkins-data" includes invalid characters for a local volume name, 
  # only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path